"""Negative suite: each mutation touches only what it claims, the dependency case never edits a
generated file by hand, the expectation table is evaluated strictly, and the runner always closes
its draft PR and deletes its branch (verified against a recorded httpx transport)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import httpx
import pytest
from pydantic import SecretStr

from hardening_loop.github.protocol import CheckRun
from hardening_loop.github.rest import GitHubError, GitHubRest
from hardening_loop.negative import (
    ALL_CHECKS,
    CASES,
    CHECK_BUILD,
    CHECK_MANIFEST,
    CHECK_SMOKE,
    REGRESSION_PIN,
    MutationError,
    NegativeRunner,
    all_expected_completed,
    evaluate,
    mutate,
)

DOCKERFILE = """FROM python:3.11 AS python-base
RUN true
FROM python-base AS python-common
RUN true
FROM python-common AS lean
COPY requirements/base.txt requirements/
USER superset
FROM lean AS ci
USER root
"""


def _checkout(tmp_path: Path) -> Path:
    src = tmp_path / "superset"
    (src / "superset").mkdir(parents=True)
    (src / "requirements").mkdir()
    (src / "Dockerfile").write_text(DOCKERFILE)
    (src / "superset" / "config.py").write_text("SECRET_KEY = 'x'\n")
    (src / "requirements" / "base.in").write_text(
        "# pins\nurllib3>=2.6.3,<3.0.0\nwerkzeug>=3.1.6,<4.0.0\n"
    )
    (src / "requirements" / "base.txt").write_text(
        "# autogenerated\nurllib3==2.6.3\n    # via requests\n"
    )
    (src / "requirements" / "development.txt").write_text("# autogenerated\nurllib3==2.6.3\n")
    return src


def test_broken_build_inserts_run_false_in_lean_stage(tmp_path: Path) -> None:
    src = _checkout(tmp_path)
    assert mutate("broken-build", src) == ["Dockerfile"]
    lines = (src / "Dockerfile").read_text().splitlines()
    i = lines.index("FROM python-common AS lean")
    assert lines[i + 1].startswith("RUN false")
    assert "RUN false" not in "".join(lines[:i])  # earlier stages untouched


def test_broken_build_requires_lean_stage(tmp_path: Path) -> None:
    src = _checkout(tmp_path)
    (src / "Dockerfile").write_text("FROM python:3.11\n")
    with pytest.raises(MutationError, match="lean"):
        mutate("broken-build", src)


def test_broken_runtime_appends_import_time_error(tmp_path: Path) -> None:
    src = _checkout(tmp_path)
    assert mutate("broken-runtime", src) == ["superset/config.py"]
    text = (src / "superset" / "config.py").read_text()
    assert text.startswith("SECRET_KEY") and text.rstrip().endswith(
        'raise RuntimeError("ci-negative: broken-runtime")'
    )


def test_dependency_regression_edits_source_input_and_regenerates(tmp_path: Path) -> None:
    src = _checkout(tmp_path)
    calls: list[Path] = []

    def fake_regen(root: Path) -> None:
        calls.append(root)
        base_in = (root / "requirements" / "base.in").read_text()
        assert REGRESSION_PIN in base_in and "urllib3>=2.6.3" not in base_in
        (root / "requirements" / "base.txt").write_text(
            f"# autogenerated\n{REGRESSION_PIN}\n    # via requests\n"
        )
        (root / "requirements" / "development.txt").write_text(
            f"# autogenerated\n{REGRESSION_PIN}\n"
        )

    changed = mutate("dependency-regression", src, regenerate=fake_regen)
    assert calls == [src]
    assert changed == [
        "requirements/base.in",
        "requirements/base.txt",
        "requirements/development.txt",
    ]
    assert (src / "requirements" / "base.in").read_text().splitlines()[1] == REGRESSION_PIN


def test_dependency_regression_fails_if_generator_changes_nothing(tmp_path: Path) -> None:
    src = _checkout(tmp_path)
    with pytest.raises(MutationError, match=r"did not change requirements/base\.txt"):
        mutate("dependency-regression", src, regenerate=lambda root: None)


def test_dependency_regression_fails_if_pin_missing_from_output(tmp_path: Path) -> None:
    src = _checkout(tmp_path)

    def regen(root: Path) -> None:
        (root / "requirements" / "base.txt").write_text("# autogenerated\nurllib3==2.6.4\n")

    with pytest.raises(MutationError, match=f"does not pin {REGRESSION_PIN}"):
        mutate("dependency-regression", src, regenerate=regen)


def test_ignore_file_and_unapproved_vex(tmp_path: Path) -> None:
    src = _checkout(tmp_path)
    assert mutate("ignore-file", src) == [".trivyignore"]
    assert (src / ".trivyignore").read_text().startswith("# ci-negative")
    [rel] = mutate("unapproved-vex", src)
    doc = json.loads((src / rel).read_text())
    assert rel.startswith("security/vex/approved/") and "x-approval" not in doc
    assert doc["statements"][0]["status"] == "not_affected"


def test_expectation_table_covers_only_known_checks() -> None:
    for case in CASES.values():
        assert set(case.expect) <= set(ALL_CHECKS), case.name
        assert CHECK_MANIFEST in case.expect, "every case says what the manifest may conclude"
    assert CASES["broken-build"].expect[CHECK_BUILD] == {"failure"}
    assert CASES["broken-runtime"].expect[CHECK_SMOKE] == {"failure"}
    assert all(v == {"success"} for v in CASES["dependency-regression"].expect.values())


def _run(name: str, conclusion: str | None, status: str = "completed") -> CheckRun:
    return CheckRun(name=name, status=status, conclusion=conclusion)


def test_evaluate_strict_on_missing_pending_and_wrong() -> None:
    case = CASES["broken-build"]
    runs = [
        _run(n, "skipped")
        for n in ALL_CHECKS
        if n not in {CHECK_BUILD, "forbid-ignore-files", "vex-lint"}
    ]
    runs += [_run(CHECK_BUILD, "failure"), _run("forbid-ignore-files", "success")]
    runs += [_run("vex-lint", None, status="in_progress")]
    assert not all_expected_completed(case, runs)
    results, failures = evaluate(case, runs)
    assert results[CHECK_BUILD] == "failure"
    assert failures == ["vex-lint: still in_progress"]

    runs[-1] = _run("vex-lint", "success")
    assert all_expected_completed(case, runs)
    assert evaluate(case, runs)[1] == []

    runs[0] = _run(runs[0].name, "success")  # a skipped job unexpectedly ran and passed
    _, failures = evaluate(case, runs)
    assert failures == [f"{runs[0].name}: success, expected one of ['skipped']"]

    _, failures = evaluate(case, [r for r in runs if r.name != CHECK_MANIFEST])
    assert f"{CHECK_MANIFEST}: no check run reported" in failures


def test_evaluate_prefers_completed_rerun_over_stale_pending() -> None:
    case = CASES["ignore-file"]
    runs = [_run(n, None, status="queued") for n in case.expect] + [
        _run(n, "failure") for n in case.expect
    ]
    results, failures = evaluate(case, runs)
    assert failures == [] and all(v == "failure" for v in results.values())


class _FakeGitHub(httpx.BaseTransport):
    """Enough of the REST API for NegativeRunner: PR create/close/comment, branch delete, check runs
    that complete on the second poll."""

    def __init__(self) -> None:
        self.calls: list[str] = []
        self.polls = 0

    def handle_request(self, request: httpx.Request) -> httpx.Response:
        path = request.url.path
        self.calls.append(f"{request.method} {path}")
        if request.method == "POST" and path.endswith("/pulls"):
            body = json.loads(request.content)
            assert body["draft"] is True and body["base"] == "main"
            return httpx.Response(201, json=_pr_json(77, body["head"]))
        if request.method == "PATCH" and path.endswith("/pulls/77"):
            assert json.loads(request.content) == {"state": "closed"}
            return httpx.Response(200, json=_pr_json(77, "x", state="closed"))
        if request.method == "POST" and path.endswith("/issues/77/comments"):
            return httpx.Response(201, json={})
        if request.method == "DELETE" and "/git/refs/heads/" in path:
            return httpx.Response(204)
        if path.endswith("/check-runs"):
            self.polls += 1
            done = self.polls >= 2
            case = CASES["ignore-file"]
            runs = [
                {
                    "name": n,
                    "status": "completed" if done else "in_progress",
                    "conclusion": ("failure" if done else None),
                    "html_url": "https://x",
                }
                for n in case.expect
            ]
            return httpx.Response(200, json={"check_runs": runs})
        return httpx.Response(404, json={"message": f"unexpected {request.method} {path}"})


def _pr_json(number: int, head: str, state: str = "open") -> dict[str, Any]:
    return {
        "number": number,
        "html_url": f"https://github.com/Hunter-1298/superset/pull/{number}",
        "title": "t",
        "state": state,
        "merged": False,
        "merge_commit_sha": None,
        "base": {"ref": "main"},
        "head": {"ref": head, "sha": "f" * 40, "repo": {"full_name": "Hunter-1298/superset"}},
        "user": {"login": "hunter"},
    }


def test_runner_opens_draft_waits_evaluates_and_cleans_up(tmp_path: Path) -> None:
    fake = _FakeGitHub()
    gh = GitHubRest(SecretStr("t"), transport=fake)
    slept: list[float] = []
    runner = NegativeRunner(
        gh, repo="Hunter-1298/superset", work_dir=tmp_path, poll_seconds=1.0, sleep=slept.append
    )
    report = runner.run(
        "ignore-file", branch="ci-negative/ignore-file-1", head_sha="f" * 40, run_url="https://run"
    )
    assert report.passed and report.expectation_failures == []
    assert report.pr_url == "https://github.com/Hunter-1298/superset/pull/77"
    assert slept == [1.0]
    assert fake.calls[0] == "POST /repos/Hunter-1298/superset/pulls"
    assert fake.calls[-2:] == [
        "PATCH /repos/Hunter-1298/superset/pulls/77",
        "DELETE /repos/Hunter-1298/superset/git/refs/heads/ci-negative/ignore-file-1",
    ]
    payload = report.to_dict()
    assert payload["schema"] == "hardening-loop/ci-negative-report/v1"
    assert payload["check_results"]["forbid-ignore-files"] == "failure"


def test_runner_never_touches_upstream(tmp_path: Path) -> None:
    gh = GitHubRest(SecretStr("t"), transport=_FakeGitHub())
    runner = NegativeRunner(gh, repo="apache/superset", work_dir=tmp_path, sleep=lambda s: None)
    with pytest.raises(GitHubError, match="refusing to touch 'apache/superset'"):
        runner.run("ignore-file", branch="b", head_sha="f" * 40, run_url="u")


def test_workflow_job_names_match_expectation_table() -> None:
    """The controller's ci-negative.yml enumerates the same case names as CASES."""
    text = (
        Path(__file__).resolve().parents[1] / ".github" / "workflows" / "ci-negative.yml"
    ).read_text()
    for name in CASES:
        assert f'"{name}"' in text, name
